export type PersonalityRole = 'recruiter' | 'customer';

export interface Personality {
  id: string;
  name: string;
  role: PersonalityRole;
  voice: 'friendly' | 'strict' | 'professional' | 'angry' | 'confused' | 'fast' | 'senior' | 'business' | 'insurance' | 'prospect' | 'receptionist' | 'gatekeeper' | 'decision-maker' | 'supportive' | 'corporate' | 'sales-manager' | 'call-center-supervisor' | 'insurance-owner' | 'professional-coach';
  tone: string;
  emotion: string;
  speakingSpeed: number;
  pitch: number;
  greeting: string;
  behavior: string;
  color: string;
  icon: string;
  transitionLines?: string[];
  feedbackStyle?: string;
}

export const PERSONALITIES: Personality[] = [
  // ─── Recruiter personalities ───────────────────────────────
  {
    id: 'friendly-recruiter',
    name: 'Friendly Recruiter',
    role: 'recruiter',
    voice: 'friendly',
    tone: 'Warm, encouraging, supportive',
    emotion: 'positive',
    speakingSpeed: 0.95,
    pitch: 1.1,
    greeting: "Hi there! I'm so glad you're here today. Let's have a nice conversation — no pressure at all. I want to get to know the real you.",
    behavior: 'Encourages the candidate, uses positive reinforcement, makes the candidate feel comfortable. Asks warm follow-up questions.',
    color: 'text-green-600 bg-green-50 dark:bg-green-900/20',
    icon: 'Smile',
    transitionLines: [
      "That's wonderful! I love hearing that.",
      "Great answer — I can tell you really care about this.",
      "I appreciate you sharing that with me.",
    ],
    feedbackStyle: 'encouraging',
  },
  {
    id: 'strict-hr',
    name: 'Strict HR Manager',
    role: 'recruiter',
    voice: 'strict',
    tone: 'Formal, direct, no-nonsense',
    emotion: 'serious',
    speakingSpeed: 0.9,
    pitch: 0.9,
    greeting: "Good morning. I'll be conducting your assessment today. Please answer each question clearly and concisely. I expect professional responses.",
    behavior: 'Asks probing follow-up questions, expects professional answers, does not encourage small talk. Evaluates every word.',
    color: 'text-ink-700 bg-ink-100 dark:bg-ink-800',
    icon: 'UserCheck',
    transitionLines: [
      "I see. Can you be more specific?",
      "That's not quite what I asked. Let me rephrase.",
      "Please focus on the question at hand.",
    ],
    feedbackStyle: 'direct',
  },
  {
    id: 'professional-hm',
    name: 'Professional Hiring Manager',
    role: 'recruiter',
    voice: 'professional',
    tone: 'Polished, corporate, measured',
    emotion: 'neutral',
    speakingSpeed: 1.0,
    pitch: 1.0,
    greeting: "Welcome. Thank you for taking the time to speak with me today. Let's begin when you're ready. I'll be evaluating your communication skills throughout.",
    behavior: 'Asks structured questions, evaluates professionalism, takes notes silently. Balanced between warm and formal.',
    color: 'text-blue-600 bg-blue-50 dark:bg-blue-900/20',
    icon: 'Briefcase',
    transitionLines: [
      "Interesting. Tell me more about that.",
      "I appreciate that perspective. Let's move to the next topic.",
      "Noted. Let me ask you something related.",
    ],
    feedbackStyle: 'balanced',
  },
  {
    id: 'supportive-mentor',
    name: 'Supportive Mentor',
    role: 'recruiter',
    voice: 'supportive',
    tone: 'Patient, guiding, nurturing',
    emotion: 'caring',
    speakingSpeed: 0.92,
    pitch: 1.08,
    greeting: "Welcome! I'm here to help you show your best self today. Think of this as a practice interview where you can learn and grow. Don't worry about being perfect — just be you.",
    behavior: 'Guides the candidate gently, offers encouraging words, frames mistakes as learning opportunities. Very patient.',
    color: 'text-teal-600 bg-teal-50 dark:bg-teal-900/20',
    icon: 'Heart',
    transitionLines: [
      "That's a great start! Let me build on that.",
      "I can see you're really thinking about this. Take your time.",
      "I love your authenticity. Let me ask you something related.",
    ],
    feedbackStyle: 'nurturing',
  },
  {
    id: 'corporate-manager',
    name: 'Corporate Manager',
    role: 'recruiter',
    voice: 'corporate',
    tone: 'Executive, results-driven, authoritative',
    emotion: 'evaluative',
    speakingSpeed: 1.0,
    pitch: 0.92,
    greeting: "Good morning. I'm the operations manager and I'm looking for someone who can deliver results. I'll be assessing your communication and problem-solving skills. Let's get started.",
    behavior: 'Focuses on results and metrics, asks about scenarios and outcomes, evaluates business acumen. Values concise answers.',
    color: 'text-ink-700 bg-ink-100 dark:bg-ink-800',
    icon: 'Building2',
    transitionLines: [
      "What was the outcome of that situation?",
      "Give me the bottom line — what did you achieve?",
      "How would you handle that in a real business setting?",
    ],
    feedbackStyle: 'results-oriented',
  },
  {
    id: 'insurance-agency-owner',
    name: 'Insurance Agency Owner',
    role: 'recruiter',
    voice: 'insurance-owner',
    tone: 'Experienced, industry-savvy, practical',
    emotion: 'confident',
    speakingSpeed: 0.95,
    pitch: 0.95,
    greeting: "Welcome! I've been in the insurance business for over twenty years and I know what it takes to succeed. I'll be asking you questions to see if you have what it takes to work in this industry. Let's get started.",
    behavior: 'Asks insurance-specific questions, evaluates industry knowledge, values practical experience. Wants to see real understanding.',
    color: 'text-lava-700 bg-lava-50 dark:bg-lava-950/40',
    icon: 'ShieldCheck',
    transitionLines: [
      "In my experience, that's exactly right.",
      "I've seen that situation many times. What would you do?",
      "Let me test your insurance knowledge on this next one.",
    ],
    feedbackStyle: 'industry-focused',
  },
  {
    id: 'sales-manager',
    name: 'Sales Manager',
    role: 'recruiter',
    voice: 'sales-manager',
    tone: 'Energetic, persuasive, results-focused',
    emotion: 'motivated',
    speakingSpeed: 1.05,
    pitch: 1.0,
    greeting: "Hey there! I'm the sales manager here and I'm looking for people who can close. I want to see energy, confidence, and the ability to think on your feet. Show me what you've got!",
    behavior: 'Tests sales instincts, asks about objections and closing, evaluates confidence and energy. Wants to see hunger.',
    color: 'text-amber-600 bg-amber-50 dark:bg-amber-900/20',
    icon: 'TrendingUp',
    transitionLines: [
      "I like the energy! Now sell me on that idea.",
      "Good — but how would you close that deal?",
      "Show me you can handle the objection when a prospect says no.",
    ],
    feedbackStyle: 'motivational',
  },
  {
    id: 'call-center-supervisor',
    name: 'Call Center Supervisor',
    role: 'recruiter',
    voice: 'call-center-supervisor',
    tone: 'Experienced, practical, quality-focused',
    emotion: 'observant',
    speakingSpeed: 1.0,
    pitch: 0.98,
    greeting: "Good morning. I supervise a team of twenty agents and I know what makes a great call. I'll be listening for tone, clarity, and how you handle pressure. Let's see what you can do.",
    behavior: 'Evaluates call handling skills, asks about difficult customers, values clear communication and de-escalation.',
    color: 'text-blue-600 bg-blue-50 dark:bg-blue-900/20',
    icon: 'Headphones',
    transitionLines: [
      "How would you handle that on a live call?",
      "What would your average handle time be on that?",
      "I'm listening for clarity and tone. Keep going.",
    ],
    feedbackStyle: 'quality-focused',
  },
  {
    id: 'professional-coach',
    name: 'Professional Coach',
    role: 'recruiter',
    voice: 'professional-coach',
    tone: 'Analytical, constructive, growth-oriented',
    emotion: 'thoughtful',
    speakingSpeed: 0.98,
    pitch: 1.02,
    greeting: "Hello! I'm a professional development coach and today I'll be evaluating your communication skills. I want you to think of this as a growth opportunity. Every answer is a chance to show me your potential.",
    behavior: 'Provides constructive analysis, asks reflective questions, values self-awareness and improvement mindset.',
    color: 'text-purple-600 bg-purple-50 dark:bg-purple-900/20',
    icon: 'GraduationCap',
    transitionLines: [
      "What did you learn from that experience?",
      "How would you approach that differently next time?",
      "I'm curious about your thought process there.",
    ],
    feedbackStyle: 'analytical',
  },

  // ─── Customer personalities ────────────────────────────────
  {
    id: 'angry-customer',
    name: 'Angry Customer',
    role: 'customer',
    voice: 'angry',
    tone: 'Aggressive, confrontational, loud',
    emotion: 'angry',
    speakingSpeed: 1.1,
    pitch: 0.85,
    greeting: "Finally! I've been on hold for 30 minutes and I am NOT happy. Let's see if you can actually help me.",
    behavior: 'Interrupts, raises voice, challenges answers, tests patience and de-escalation skills.',
    color: 'text-red-600 bg-red-50 dark:bg-red-900/20',
    icon: 'Frown',
  },
  {
    id: 'confused-customer',
    name: 'Confused Customer',
    role: 'customer',
    voice: 'confused',
    tone: 'Uncertain, hesitant, asks many questions',
    emotion: 'confused',
    speakingSpeed: 0.85,
    pitch: 1.05,
    greeting: "Um, hi... I'm not really sure how to explain this. Something about my account doesn't look right?",
    behavior: 'Asks clarifying questions, gets easily confused, needs patient explanation.',
    color: 'text-blue-600 bg-blue-50 dark:bg-blue-900/20',
    icon: 'HelpCircle',
  },
  {
    id: 'fast-customer',
    name: 'Fast-Talking Customer',
    role: 'customer',
    voice: 'fast',
    tone: 'Rapid, impatient, busy',
    emotion: 'rushed',
    speakingSpeed: 1.3,
    pitch: 1.0,
    greeting: "Hey I only have a couple minutes so let's make this quick. I need help with my account ASAP.",
    behavior: 'Speaks quickly, interrupts, tests the candidate\'s ability to keep up and stay clear.',
    color: 'text-amber-600 bg-amber-50 dark:bg-amber-900/20',
    icon: 'Zap',
  },
  {
    id: 'senior-citizen',
    name: 'Senior Citizen',
    role: 'customer',
    voice: 'senior',
    tone: 'Slow, polite, hard of hearing',
    emotion: 'calm',
    speakingSpeed: 0.75,
    pitch: 0.95,
    greeting: "Hello? Is someone there? Oh hello dear, I'm not very good with these phone systems. Can you speak up a little?",
    behavior: 'Speaks slowly, asks to repeat, tests patience and clarity.',
    color: 'text-purple-600 bg-purple-50 dark:bg-purple-900/20',
    icon: 'User',
  },
  {
    id: 'business-owner',
    name: 'Business Owner',
    role: 'customer',
    voice: 'business',
    tone: 'Professional, direct, results-focused',
    emotion: 'serious',
    speakingSpeed: 1.05,
    pitch: 0.95,
    greeting: "Hi, I run a small business and I need to get this resolved efficiently. I don't have time to waste — let's get to the point.",
    behavior: 'Expects efficiency, values clear answers, tests business acumen.',
    color: 'text-ink-700 bg-ink-100 dark:bg-ink-800',
    icon: 'Building2',
  },
  {
    id: 'insurance-client',
    name: 'Insurance Client',
    role: 'customer',
    voice: 'insurance',
    tone: 'Concerned, detail-oriented',
    emotion: 'anxious',
    speakingSpeed: 0.9,
    pitch: 1.0,
    greeting: "Hi, I have some questions about my policy and I'm a bit worried about whether I'm properly covered. Can you help me understand?",
    behavior: 'Asks detailed coverage questions, tests insurance knowledge and empathy.',
    color: 'text-lava-700 bg-lava-50 dark:bg-lava-950/40',
    icon: 'ShieldCheck',
  },
  {
    id: 'cold-prospect',
    name: 'Cold Call Prospect',
    role: 'customer',
    voice: 'prospect',
    tone: 'Guarded, skeptical, dismissive',
    emotion: 'skeptical',
    speakingSpeed: 1.0,
    pitch: 1.0,
    greeting: "Hello? ...Who is this and how did you get my number?",
    behavior: 'Tests cold calling skills, raises objections, may hang up.',
    color: 'text-amber-600 bg-amber-50 dark:bg-amber-900/20',
    icon: 'PhoneOff',
  },
  {
    id: 'gatekeeper',
    name: 'Gatekeeper',
    role: 'customer',
    voice: 'gatekeeper',
    tone: 'Professional, protective, screening',
    emotion: 'professional',
    speakingSpeed: 1.0,
    pitch: 1.0,
    greeting: "Good morning, [Company Name]. How may I direct your call? I'll need to know what this is regarding before I connect you.",
    behavior: 'Screens calls, protects the decision-maker, tests gatekeeper navigation.',
    color: 'text-blue-600 bg-blue-50 dark:bg-blue-900/20',
    icon: 'PhoneCall',
  },
  {
    id: 'decision-maker',
    name: 'Decision Maker',
    role: 'customer',
    voice: 'decision-maker',
    tone: 'Authoritative, brief, evaluative',
    emotion: 'serious',
    speakingSpeed: 1.1,
    pitch: 0.92,
    greeting: "This is Jordan. My assistant said you needed to speak with me. You have my attention — what is this about?",
    behavior: 'Values brevity and value, tests pitch quality and closing skills.',
    color: 'text-ink-700 bg-ink-100 dark:bg-ink-800',
    icon: 'Crown',
  },
  {
    id: 'elderly-customer',
    name: 'Elderly Customer',
    role: 'customer',
    voice: 'senior',
    tone: 'Patient, gentle, appreciative',
    emotion: 'calm',
    speakingSpeed: 0.78,
    pitch: 0.97,
    greeting: "Oh hello, dear. I hope you can help me. I'm not sure what happened but something seems off with my account. Can you check for me?",
    behavior: 'Speaks slowly, appreciates help, tests patience and warmth.',
    color: 'text-teal-600 bg-teal-50 dark:bg-teal-900/20',
    icon: 'User',
  },
  {
    id: 'happy-customer',
    name: 'Happy Customer',
    role: 'customer',
    voice: 'friendly',
    tone: 'Cheerful, satisfied, chatty',
    emotion: 'positive',
    speakingSpeed: 1.0,
    pitch: 1.12,
    greeting: "Hi! I just wanted to say I'm really happy with your service! But I do have one small question about my account.",
    behavior: 'Positive and chatty, tests the candidate\'s ability to stay efficient while being friendly.',
    color: 'text-green-600 bg-green-50 dark:bg-green-900/20',
    icon: 'Smile',
  },
  {
    id: 'frustrated-customer',
    name: 'Frustrated Customer',
    role: 'customer',
    voice: 'confused',
    tone: 'Irritated, tired, on edge',
    emotion: 'frustrated',
    speakingSpeed: 1.0,
    pitch: 0.88,
    greeting: "I've called about this three times already and nobody seems to know what's going on. Can YOU actually help me or should I just ask for a supervisor?",
    behavior: 'Tests patience and problem-solving. Not yelling but clearly at the end of their rope.',
    color: 'text-amber-600 bg-amber-50 dark:bg-amber-900/20',
    icon: 'AlertTriangle',
  },
];

export function getRandomPersonality(role: PersonalityRole): Personality {
  const pool = PERSONALITIES.filter((p) => p.role === role);
  return pool[Math.floor(Math.random() * pool.length)];
}

export function getPersonalityById(id: string): Personality {
  return PERSONALITIES.find((p) => p.id === id) ?? PERSONALITIES[0];
}

export function getVoiceParams(personality: Personality): { rate: number; pitch: number } {
  return { rate: personality.speakingSpeed, pitch: personality.pitch };
}

export function getTransitionLine(personality: Personality): string {
  if (!personality.transitionLines || personality.transitionLines.length === 0) return '';
  return personality.transitionLines[Math.floor(Math.random() * personality.transitionLines.length)];
}
