export type PositionId =
  | 'insurance-csr' | 'insurance-sales' | 'cold-caller' | 'sdr' | 'appointment-setter'
  | 'executive-assistant' | 'general-va' | 'customer-service' | 'receptionist'
  | 'technical-support' | 'medical-va' | 'real-estate-va' | 'ecommerce-va'
  | 'social-media-va' | 'bookkeeper' | 'data-entry';

export interface PositionConfig {
  id: PositionId;
  label: string;
  category: string;
  description: string;
  interviewQuestions: string[];
  listeningScenarios: { script: string; context: string }[];
  roleplayScenarios: { customerLine: string; context: string; emotion: string }[];
  scoringWeights: Record<string, number>;
  keyCompetencies: string[];
  coachingFocus: string[];
  recommendedLearningPath: string[];
}

export const POSITIONS: PositionConfig[] = [
  {
    id: 'insurance-csr',
    label: 'Insurance CSR',
    category: 'Insurance',
    description: 'Customer service for insurance policy servicing, billing, claims, and coverage.',
    interviewQuestions: [
      "Tell me about your experience with insurance customer service.",
      "How would you explain a deductible to a customer who doesn't understand it?",
      "A customer calls upset because their claim was denied. How do you handle it?",
      "Walk me through how you would process a policy change request.",
      "What steps would you take to verify a customer's identity before discussing their policy?",
      "How do you handle a customer who wants to cancel their policy?",
      "Explain the difference between liability and comprehensive coverage.",
      "How would you handle a billing dispute where the customer was double-charged?",
      "What would you do if a customer asked for proof of insurance urgently?",
      "Describe how you would help a customer add a new driver to their policy.",
      "How do you stay updated on insurance regulations and policy changes?",
      "A customer is confused about their renewal premium increase. How do you explain it?",
      "How would you handle a mortgage company calling for proof of insurance?",
      "What would you do if a customer requested a vehicle replacement on their policy?",
      "How do you prioritize multiple urgent policy servicing requests?",
    ],
    listeningScenarios: [
      { script: "Hi, I'm calling about my auto insurance policy number AX-4471. I recently moved to a new address in downtown Austin, and I wanted to check if my premium will change. Also, I'd like to add comprehensive coverage to my plan.", context: 'Policy update inquiry' },
      { script: "I need proof of insurance for my mortgage company by Friday. My lender is First National Bank, loan number 7842-CC. Can you fax or email the declarations page to them?", context: 'Mortgage/proof of insurance request' },
      { script: "My claim was denied and I don't understand why. The claim number is CL-22910, filed on October 15th. The adjuster said something about insufficient documentation but I submitted everything they asked for.", context: 'Claim denial dispute' },
    ],
    roleplayScenarios: [
      { customerLine: "I've been on hold for 45 minutes and now you're telling me my claim is denied? This is ridiculous!", context: 'Angry customer with denied claim', emotion: 'angry' },
      { customerLine: "Hi, I just got my renewal notice and my premium went up by $30 a month. I haven't had any accidents, so why did it increase?", context: 'Renewal premium increase inquiry', emotion: 'confused' },
      { customerLine: "I want to cancel my policy effective immediately. I found a cheaper rate elsewhere and I don't want to hear any sales pitches.", context: 'Policy cancellation request', emotion: 'firm' },
    ],
    scoringWeights: { Listening: 1.2, 'Customer Service': 1.3, 'Insurance Knowledge': 1.4, Professionalism: 1.1, Empathy: 1.1, Communication: 1.0 },
    keyCompetencies: ['Insurance terminology', 'Policy servicing', 'Claims handling', 'Billing accuracy', 'Empathy'],
    coachingFocus: ['Insurance vocabulary precision', 'De-escalation with upset policyholders', 'Clear coverage explanations'],
    recommendedLearningPath: ['Insurance 101 fundamentals', 'Claims processing workflow', 'Customer de-escalation techniques', 'Policy servicing best practices'],
  },
  {
    id: 'insurance-sales',
    label: 'Insurance Sales Agent',
    category: 'Insurance',
    description: 'Selling insurance products, handling objections, and closing sales.',
    interviewQuestions: [
      "Tell me about your insurance sales experience.",
      "How do you handle a prospect who says insurance is too expensive?",
      "Walk me through your process for quoting a new auto policy.",
      "How would you cross-sell a home insurance policy to an existing auto customer?",
      "What's your approach to following up on warm leads?",
      "How do you handle the objection 'I already have insurance'?",
      "Describe how you would close a sale with a hesitant prospect.",
      "How do you build rapport with a cold lead in the first 30 seconds?",
      "What strategies do you use to overcome price objections?",
      "How would you explain the value of umbrella coverage to a prospect?",
      "Tell me about a time you turned a 'no' into a 'yes' in insurance sales.",
      "How do you maintain a pipeline of potential insurance clients?",
      "What would you do if a prospect kept comparing you to a competitor's lower rate?",
      "How do you handle a prospect who wants to 'think about it'?",
      "Describe your follow-up process after an initial insurance quote.",
    ],
    listeningScenarios: [
      { script: "I'm shopping around for auto insurance. I currently pay $89 a month with Geico. Can you beat that rate? I have a clean driving record and I'm 34 years old.", context: 'Price-shopping prospect' },
      { script: "My friend recommended you. I just bought a new home and I'm wondering if I should bundle it with my auto policy. What kind of discount would I get?", context: 'Warm referral, bundling opportunity' },
      { script: "I've been with State Farm for 15 years. Why should I switch to your company? What makes your coverage better than what I already have?", context: 'Loyalty objection' },
    ],
    roleplayScenarios: [
      { customerLine: "Look, I appreciate the call but I'm not interested. I already have insurance and I don't want to switch.", context: 'Cold call with immediate resistance', emotion: 'dismissive' },
      { customerLine: "Your rate is $40 higher than what I was quoted online. Why would I pay more for the same coverage?", context: 'Price objection', emotion: 'skeptical' },
      { customerLine: "Hmm, that actually sounds like a decent deal. But I need to talk to my wife before making any decisions.", context: 'Interested but hesitant', emotion: 'interested' },
    ],
    scoringWeights: { 'Cold Calling Skills': 1.3, Persuasion: 1.3, 'Insurance Knowledge': 1.2, Confidence: 1.2, Communication: 1.1, Listening: 1.0 },
    keyCompetencies: ['Sales techniques', 'Objection handling', 'Insurance products', 'Closing skills', 'Pipeline management'],
    coachingFocus: ['Objection handling frameworks', 'Value-based selling', 'Closing techniques'],
    recommendedLearningPath: ['Insurance sales fundamentals', 'Objection handling scripts', 'Cross-selling strategies', 'Pipeline management systems'],
  },
  {
    id: 'cold-caller',
    label: 'Cold Caller',
    category: 'Sales',
    description: 'Outbound calling, gatekeeper navigation, and appointment setting.',
    interviewQuestions: [
      "Tell me about your cold calling experience.",
      "How do you handle a gatekeeper who won't let you through to the decision maker?",
      "What's your opening line when a prospect picks up the phone?",
      "How do you handle the objection 'I'm not interested' in the first 10 seconds?",
      "Walk me through your process for leaving an effective voicemail.",
      "How do you handle a busy prospect who says they don't have time?",
      "What discovery questions do you ask to qualify a cold lead?",
      "How do you handle price objections during a cold call?",
      "What would you do if a prospect compares you to a competitor?",
      "How do you maintain energy and motivation after many rejections?",
      "Describe how you would schedule an appointment from a cold call.",
      "What's your rebuttal when a prospect says 'send me an email'?",
      "How do you handle a prospect who hangs up on you?",
      "What makes a cold call successful in your experience?",
      "How do you track and follow up on your cold calling results?",
    ],
    listeningScenarios: [
      { script: "Hello? Yes, this is he. I wasn't expecting a call — what is this about exactly? I'm in the middle of something.", context: 'Surprised prospect' },
      { script: "I'm the office manager here. Mr. Johnson is in a meeting and can't be disturbed. Can I take a message?", context: 'Gatekeeper screening' },
      { script: "Look, we already have a vendor for that and we're happy with them. I don't see why I should switch.", context: 'Competitor objection' },
    ],
    roleplayScenarios: [
      { customerLine: "I'm not interested. Take me off your call list and don't call here again.", context: 'Immediate rejection', emotion: 'annoyed' },
      { customerLine: "I'm the receptionist. Mr. Davis is in a meeting. What is this regarding? I can't put you through without knowing.", context: 'Gatekeeper', emotion: 'professional' },
      { customerLine: "Okay, you have 30 seconds. Why should I keep listening?", context: 'Time-pressured prospect', emotion: 'impatient' },
      { customerLine: "Just email me the details and I'll look when I get a chance. I really can't talk right now.", context: 'Brush-off to email', emotion: 'dismissive' },
      { customerLine: "How much does this cost? Just give me a number before you waste any more of my time.", context: 'Early price objection', emotion: 'skeptical' },
    ],
    scoringWeights: { 'Cold Calling Skills': 1.4, Confidence: 1.3, Persuasion: 1.2, 'Tone Consistency': 1.1, Communication: 1.1, Listening: 1.0 },
    keyCompetencies: ['Gatekeeper navigation', 'Objection handling', 'Voicemail technique', 'Discovery questions', 'Energy maintenance'],
    coachingFocus: ['Call opening hooks', 'Gatekeeper bypass strategies', 'Objection rebuttals'],
    recommendedLearningPath: ['Cold calling fundamentals', 'Gatekeeper navigation', 'Objection handling scripts', 'Voicemail best practices'],
  },
  {
    id: 'sdr',
    label: 'SDR / Sales Development Rep',
    category: 'Sales',
    description: 'Outbound prospecting, lead qualification (BANT), discovery, and booking qualified meetings for account executives.',
    interviewQuestions: [
      "Tell me about your experience as an SDR or in outbound sales development.",
      "Walk me through your opening line on a cold outbound call to a prospect who has never heard of us.",
      "How do you research and prioritize which accounts and prospects to call each day?",
      "What discovery questions do you ask to qualify a lead using a framework like BANT?",
      "How do you handle the objection 'Just send me an email' and still move toward a meeting?",
      "A prospect says 'We already use a competitor.' How do you keep the conversation going?",
      "How do you get past a gatekeeper to reach the decision maker?",
      "What's your process for booking a qualified meeting and making sure the prospect actually shows up?",
      "How do you personalize a cold outreach at scale without sounding like a script?",
      "Describe your multi-touch cadence — how many touches, which channels, over how many days?",
      "How do you handle 'We don't have budget right now'?",
      "How do you decide a lead is NOT qualified and should be disqualified?",
      "How do you log calls and update the CRM so the account executive has what they need?",
      "How do you stay motivated and keep your energy up after a morning of rejections?",
      "Tell me about a time you booked a meeting with a hard-to-reach prospect. What did you do?",
    ],
    listeningScenarios: [
      { script: "Hi, thanks for picking up. I saw your team just expanded to three new markets, so I figured reaching out made sense. Before I take more of your time — are you the right person who owns the outbound sales tooling decisions, or should I be talking to someone else?", context: 'SDR qualifying the right contact' },
      { script: "This is a bad time honestly, we're heads-down on a launch. But quickly — what is this about? If it's another sales tool I'll tell you now we looked at two of those last quarter and passed.", context: 'Busy, skeptical prospect' },
      { script: "Okay you got my attention. We're a 40-person team, we use HubSpot, and our biggest problem right now is that reps waste time on unqualified leads. If you can help with that, I'd take a 20-minute call next week.", context: 'Qualified prospect ready to book' },
    ],
    roleplayScenarios: [
      { customerLine: "I don't take cold calls. How did you even get this number? Just send me something by email.", context: 'Cold open, deflecting to email', emotion: 'dismissive' },
      { customerLine: "You've got thirty seconds. What do you do and why should I care?", context: 'Time-pressured decision maker', emotion: 'impatient' },
      { customerLine: "We're actually pretty happy with our current setup. I'm not looking to switch anything right now.", context: 'Status-quo / competitor objection', emotion: 'skeptical' },
      { customerLine: "This sounds interesting, but I'm not the one who makes this call. You'd need to talk to our VP of Sales.", context: 'Referral to the real decision maker', emotion: 'neutral' },
      { customerLine: "Alright, a 20-minute call could work. But I've had reps no-show on me before, so make it worth my time.", context: 'Booking the meeting and confirming commitment', emotion: 'interested' },
    ],
    scoringWeights: { 'Cold Calling Skills': 1.4, 'Appointment Setting Skills': 1.3, Persuasion: 1.2, Confidence: 1.2, Communication: 1.1, Listening: 1.1 },
    keyCompetencies: ['Outbound prospecting', 'Lead qualification (BANT)', 'Discovery questioning', 'Objection handling', 'Meeting booking', 'CRM hygiene'],
    coachingFocus: ['Personalized cold openers', 'Qualification frameworks', 'Turning objections into meetings', 'Confirming and protecting booked meetings'],
    recommendedLearningPath: ['Outbound prospecting fundamentals', 'BANT and discovery questioning', 'Objection handling for SDRs', 'Multi-touch cadence design', 'Booking meetings that show up'],
  },
  {
    id: 'appointment-setter',
    label: 'Appointment Setter',
    category: 'Sales',
    description: 'Scheduling appointments, confirming meetings, and managing calendars.',
    interviewQuestions: [
      "Tell me about your appointment setting experience.",
      "How do you handle a prospect who keeps rescheduling?",
      "What's your process for confirming an appointment the day before?",
      "How would you handle a prospect who no-shows?",
      "Walk me through how you would schedule a meeting between a sales rep and a prospect.",
      "How do you handle objections when a prospect says they're too busy?",
      "What information do you collect when setting an appointment?",
      "How do you ensure the prospect actually shows up for the appointment?",
      "How would you handle a prospect who wants to reschedule at the last minute?",
      "What follow-up process do you use after setting an appointment?",
      "How do you handle a prospect who seems interested but won't commit to a time?",
      "Describe how you would set appointments for a busy sales team.",
      "What would you do if a prospect gave you the wrong phone number?",
      "How do you prioritize which appointments to set first?",
      "What makes an appointment setter successful in your view?",
    ],
    listeningScenarios: [
      { script: "Sure, I'd be happy to set up a time to talk. I work during the day though, so it would have to be in the evening or on the weekend. What times do you have available?", context: 'Scheduling with availability constraints' },
      { script: "I said I'd call back but honestly I've been really busy. Can we push this to next week? I just don't have time this week.", context: 'Rescheduling request' },
      { script: "I'm interested but I need to check with my business partner first. Can you call me back on Thursday afternoon around 2?", context: 'Conditional interest' },
    ],
    roleplayScenarios: [
      { customerLine: "I'm interested but I'm really busy right now. Can you just send me an email with the details?", context: 'Email deflection', emotion: 'polite' },
      { customerLine: "I said I'd talk to you but I didn't realize it would be a 30-minute call. I only have 5 minutes.", context: 'Time-constrained prospect', emotion: 'rushed' },
      { customerLine: "Sure, let's schedule something. But I might need to reschedule depending on my workload, is that okay?", context: 'Non-committal prospect', emotion: 'casual' },
    ],
    scoringWeights: { 'Appointment Setting Skills': 1.4, 'Customer Service': 1.1, Confidence: 1.1, Communication: 1.1, Listening: 1.0, Professionalism: 1.1 },
    keyCompetencies: ['Scheduling accuracy', 'Confirmation techniques', 'Objection handling', 'Follow-up discipline', 'Calendar management'],
    coachingFocus: ['Securing firm commitments', 'Confirmation call scripts', 'No-show prevention'],
    recommendedLearningPath: ['Appointment setting fundamentals', 'Confirmation techniques', 'Calendar management tools', 'Follow-up systems'],
  },
  {
    id: 'executive-assistant',
    label: 'Executive Assistant',
    category: 'Administrative',
    description: 'Calendar management, executive communication, and professional coordination.',
    interviewQuestions: [
      "Tell me about your experience supporting executives.",
      "How do you handle conflicting meeting requests from multiple executives?",
      "Walk me through how you would prioritize an executive's inbox.",
      "How would you handle a last-minute schedule change from your executive?",
      "Describe how you would coordinate travel for an executive.",
      "How do you handle confidential information?",
      "What's your approach to managing an executive's calendar?",
      "How would you handle a meeting where the executive is running late?",
      "Describe how you would prioritize tasks when everything seems urgent.",
      "How do you communicate professionally on behalf of an executive?",
      "How would you handle a difficult colleague who demands the executive's time?",
      "What tools do you use for task and calendar management?",
      "How do you ensure nothing falls through the cracks?",
      "Describe how you would prepare an executive for an important meeting.",
      "How do you handle working with multiple time zones?",
    ],
    listeningScenarios: [
      { script: "Hi, this is Sarah from the CEO's office. Mark needs to move the 2 PM strategy meeting to 3:30 PM tomorrow. Also, he wants to add a 15-minute prep call with the CFO beforehand. Can you update the calendar and notify the attendees?", context: 'Complex rescheduling request' },
      { script: "I'm calling from the London office. Our managing director needs to speak with your executive sometime this week. She's available Tuesday or Wednesday between 9 AM and noon GMT. What works on your end?", context: 'Cross-timezone coordination' },
      { script: "The board meeting has been moved up by two days. We need to reschedule everything on the executive's calendar for Thursday and Friday. Can you make it work?", context: 'Urgent rescheduling' },
    ],
    roleplayScenarios: [
      { customerLine: "I need to speak with Mr. Thompson right now. It's urgent and I can't wait for a callback. Can you put me through?", context: 'Urgent interruption', emotion: 'demanding' },
      { customerLine: "I'm trying to schedule a meeting with your executive but their calendar seems completely full for the next three weeks. How do we make this work?", context: 'Scheduling conflict', emotion: 'frustrated' },
      { customerLine: "I sent an email last week and never got a response. I need to know if the executive has reviewed my proposal. Can you check?", context: 'Follow-up on unanswered email', emotion: 'anxious' },
    ],
    scoringWeights: { Professionalism: 1.4, Communication: 1.3, 'Problem Solving': 1.2, 'Critical Thinking': 1.2, Listening: 1.1, Confidence: 1.0 },
    keyCompetencies: ['Calendar management', 'Professional communication', 'Task prioritization', 'Confidentiality', 'Cross-timezone coordination'],
    coachingFocus: ['Professional email tone', 'Diplomatic scheduling', 'Executive-level communication'],
    recommendedLearningPath: ['Executive assistance fundamentals', 'Calendar management mastery', 'Professional business writing', 'Stakeholder communication'],
  },
  {
    id: 'general-va',
    label: 'General Virtual Assistant',
    category: 'Administrative',
    description: 'General administrative support, email management, and data tasks.',
    interviewQuestions: [
      "Tell me about your virtual assistant experience.",
      "How do you manage your time when working remotely?",
      "What tools do you use for task management?",
      "How would you handle a client who changes priorities frequently?",
      "Describe how you manage multiple clients simultaneously.",
      "How do you ensure clear communication when working remotely?",
      "What's your approach to organizing digital files?",
      "How would you handle a task you've never done before?",
      "How do you manage email inbox for a busy client?",
      "What would you do if a client was unhappy with your work?",
      "How do you handle working across different time zones?",
      "Describe how you would research a topic for a client.",
      "How do you prioritize tasks when everything seems important?",
      "What makes a successful virtual assistant?",
      "How do you handle feedback from clients?",
    ],
    listeningScenarios: [
      { script: "Hi, I need someone to help me manage my inbox, schedule some appointments, and do some light research on competitors. I run a small marketing agency and I'm getting overwhelmed. Can you start next week?", context: 'New client onboarding' },
      { script: "I sent you a list of 50 contacts yesterday. I need them organized into a spreadsheet by industry, with notes on each one. Also, can you find their email addresses? I need this by Friday.", context: 'Data organization task' },
      { script: "I know I said the report was due Friday, but my investor meeting got moved up. Can you have it ready by Wednesday morning instead? I know it's short notice.", context: 'Rushed deadline' },
    ],
    roleplayScenarios: [
      { customerLine: "I've worked with three other VAs before and none of them worked out. What makes you different?", context: 'Skeptical new client', emotion: 'skeptical' },
      { customerLine: "I need this done today but I haven't given you all the information yet. Can you just figure it out?", context: 'Vague urgent request', emotion: 'demanding' },
      { customerLine: "The last report you sent had three typos. I'm starting to question whether this arrangement is going to work.", context: 'Dissatisfied client', emotion: 'disappointed' },
    ],
    scoringWeights: { Communication: 1.2, Professionalism: 1.2, 'Problem Solving': 1.1, Listening: 1.1, Confidence: 1.0, 'Critical Thinking': 1.1 },
    keyCompetencies: ['Time management', 'Task prioritization', 'Remote communication', 'Tool proficiency', 'Adaptability'],
    coachingFocus: ['Proactive communication', 'Task clarification', 'Remote professionalism'],
    recommendedLearningPath: ['VA fundamentals', 'Time management systems', 'Remote communication best practices', 'Client management'],
  },
  {
    id: 'customer-service',
    label: 'Customer Service Representative',
    category: 'Customer Support',
    description: 'Handling customer inquiries, complaints, and escalations.',
    interviewQuestions: [
      "Tell me about your customer service experience.",
      "How do you handle an angry customer?",
      "Describe a time you turned a negative experience into a positive one.",
      "How would you handle a customer who is cursing at you?",
      "What's your approach to de-escalating a tense situation?",
      "How do you handle a customer who wants a refund but it's against policy?",
      "How would you handle a customer whose delivery is late?",
      "Describe how you verify a customer's account.",
      "How do you handle a customer who asks to speak to a supervisor?",
      "What would you do if you didn't know the answer to a customer's question?",
      "How do you show empathy to a frustrated customer?",
      "How would you handle a customer who keeps calling about the same issue?",
      "Describe how you handle a high call volume day.",
      "How do you maintain a positive attitude with difficult customers?",
      "What does excellent customer service mean to you?",
    ],
    listeningScenarios: [
      { script: "I ordered a package two weeks ago and it still hasn't arrived. The tracking says it was delivered but I never got it. I've called twice already and nobody has helped me. This is the third time I'm calling!", context: 'Late/missing delivery' },
      { script: "I need to return this product but I lost the receipt. I bought it three weeks ago with my credit card. Can you look it up? My name is Jennifer Park.", context: 'Return without receipt' },
      { script: "I've been a customer for five years and I've never had this problem before. My account was charged twice this month and I need it fixed today, not in 3-5 business days.", context: 'Billing dispute' },
    ],
    roleplayScenarios: [
      { customerLine: "This is the worst service I've ever experienced! I want my money back right now and I want to speak to your manager!", context: 'Angry customer demanding refund', emotion: 'angry' },
      { customerLine: "I've been on hold for 45 minutes. I have things to do today. Can you just help me quickly?", context: 'Frustrated by wait time', emotion: 'frustrated' },
      { customerLine: "I'm not angry, I'm just disappointed. I expected better from your company after being a loyal customer for so long.", context: 'Disappointed loyal customer', emotion: 'disappointed' },
      { customerLine: "I've explained this three times to three different people. Why do I have to keep repeating myself? Just fix it!", context: 'Repeat contact, escalating frustration', emotion: 'frustrated' },
      { customerLine: "Wait, so you're telling me the refund will take another week? That's not acceptable. What else can you do for me?", context: 'Pushing back on policy timelines', emotion: 'firm' },
    ],
    scoringWeights: { 'Customer Service': 1.4, Empathy: 1.3, 'Problem Solving': 1.2, Listening: 1.2, Professionalism: 1.1, Communication: 1.0 },
    keyCompetencies: ['De-escalation', 'Empathy', 'Problem solving', 'Active listening', 'Patience'],
    coachingFocus: ['De-escalation techniques', 'Empathy statements', 'Solution-oriented language'],
    recommendedLearningPath: ['Customer service excellence', 'De-escalation techniques', 'Empathy in communication', 'Problem resolution frameworks'],
  },
  {
    id: 'receptionist',
    label: 'Receptionist',
    category: 'Customer Support',
    description: 'Front desk, call routing, and visitor management.',
    interviewQuestions: [
      "Tell me about your receptionist experience.",
      "How do you handle multiple phone lines ringing at once?",
      "How would you greet a visitor who arrives for a meeting?",
      "How do you handle a caller who insists on speaking to someone who is unavailable?",
      "What's your approach to managing a busy front desk?",
      "How would you handle a difficult visitor in the lobby?",
      "How do you transfer calls professionally?",
      "How would you handle a package delivery when you're on the phone?",
      "How do you maintain a welcoming environment at the front desk?",
      "How would you handle a caller who won't give their name?",
      "How do you handle confidential information at the front desk?",
      "How would you handle an unexpected VIP visitor?",
      "How do you manage the conference room schedule?",
      "How would you handle a call from an angry vendor?",
      "What makes a great receptionist?",
    ],
    listeningScenarios: [
      { script: "Hi, I'm here for my 2 o'clock appointment with Dr. Reynolds. My name is Margaret Chen. I'm a new patient so I might need to fill out some paperwork.", context: 'New visitor arrival' },
      { script: "I need to speak with the owner immediately. It's about a legal matter and I can't leave a message. I'll hold until they're available.", context: 'Insistent caller' },
      { script: "I have a delivery for Suite 400 but the receptionist up there isn't answering. I've been waiting in the lobby for 15 minutes. What should I do?", context: 'Delivery situation' },
    ],
    roleplayScenarios: [
      { customerLine: "I don't have an appointment but I need to see Mr. Davis right now. It's important. Can you tell him I'm here?", context: 'Walk-in without appointment', emotion: 'urgent' },
      { customerLine: "I've been calling all morning and nobody picks up. Is anyone actually working there today?", context: 'Frustrated caller', emotion: 'frustrated' },
      { customerLine: "I'm not giving you my name. Just connect me to the person who handles the accounts. I'll wait.", context: 'Anonymous caller', emotion: 'evasive' },
    ],
    scoringWeights: { Professionalism: 1.3, 'Customer Service': 1.2, Communication: 1.2, Listening: 1.1, Confidence: 1.0 },
    keyCompetencies: ['Professional greeting', 'Call routing', 'Multitasking', 'Visitor management', 'Diplomacy'],
    coachingFocus: ['Professional phone etiquette', 'Diplomatic gatekeeping', 'Welcoming demeanor'],
    recommendedLearningPath: ['Front desk professionalism', 'Phone etiquette mastery', 'Visitor management', 'Multitasking techniques'],
  },
  {
    id: 'technical-support',
    label: 'Technical Support',
    category: 'Customer Support',
    description: 'Troubleshooting, technical guidance, and issue resolution.',
    interviewQuestions: [
      "Tell me about your technical support experience.",
      "How do you explain technical issues to non-technical customers?",
      "How would you handle a customer whose internet is down?",
      "What's your troubleshooting process when you don't know the solution?",
      "How do you handle a frustrated customer with a technical issue?",
      "How would you walk a customer through resetting their password?",
      "How do you document technical issues for the team?",
      "How would you handle a customer who thinks they know more than you?",
      "How do you prioritize multiple technical tickets?",
      "How would you explain a complex error message in simple terms?",
      "How do you handle a customer who is crying because they lost data?",
      "How would you handle a recurring issue that's never fully resolved?",
      "How do you stay calm when a customer is frustrated with the product?",
      "How would you escalate an issue to Tier 2 support?",
      "What makes a great technical support representative?",
    ],
    listeningScenarios: [
      { script: "My computer won't connect to the WiFi. It was working fine this morning but now it just says 'no internet'. I've tried restarting it twice. I work from home and I'm losing money every minute I'm offline.", context: 'Urgent connectivity issue' },
      { script: "I keep getting this error code 0x80070002 when I try to update. I've searched online but nothing makes sense. Can you just tell me what to do in plain English?", context: 'Non-technical customer with error' },
      { script: "I think I clicked on a bad link and now my screen is frozen with a popup saying my computer has a virus. It wants me to call a number. What should I do?", context: 'Potential scam/malware' },
    ],
    roleplayScenarios: [
      { customerLine: "I've been on the phone with you people for an hour and nothing works! I'm not technical, just fix it for me!", context: 'Frustrated non-technical customer', emotion: 'frustrated' },
      { customerLine: "I already tried all of that. I've been in IT for 20 years so don't treat me like a beginner. What's the real solution?", context: 'Know-it-all customer', emotion: 'condescending' },
      { customerLine: "I'm crying because I just lost all my daughter's baby photos. Please tell me you can get them back. Please.", context: 'Distraught customer', emotion: 'distressed' },
    ],
    scoringWeights: { 'Problem Solving': 1.4, 'Technical Knowledge': 1.3, 'Customer Service': 1.2, Communication: 1.2, Listening: 1.1, Empathy: 1.0 },
    keyCompetencies: ['Troubleshooting', 'Technical communication', 'Patience', 'Documentation', 'Escalation'],
    coachingFocus: ['Plain-language technical explanations', 'Patience with non-technical users', 'Methodical troubleshooting'],
    recommendedLearningPath: ['Technical support fundamentals', 'Customer communication skills', 'Troubleshooting methodologies', 'Product knowledge deep-dive'],
  },
  {
    id: 'medical-va',
    label: 'Medical VA',
    category: 'Healthcare',
    description: 'Medical scheduling, insurance verification, and patient communication.',
    interviewQuestions: [
      "Tell me about your medical VA experience.",
      "How do you handle patient confidentiality and HIPAA compliance?",
      "How would you verify a patient's insurance coverage?",
      "How do you handle a patient who needs an urgent appointment?",
      "How would you explain a medical bill to a confused patient?",
      "How do you handle a patient who is upset about a long wait time?",
      "How would you schedule a patient for multiple procedures?",
      "How do you handle prior authorization requests?",
      "How would you handle a call from a patient's family member?",
      "How do you manage a physician's schedule efficiently?",
      "How would you handle a patient who missed their appointment?",
      "How do you handle medical terminology you're not familiar with?",
      "How would you handle a patient calling with a medical emergency?",
      "How do you maintain professionalism with anxious patients?",
      "What makes a great medical virtual assistant?",
    ],
    listeningScenarios: [
      { script: "I need to schedule a follow-up with Dr. Patel. I had surgery three weeks ago and I'm still having some pain. I also need to check if my insurance covers the visit because I just switched to Blue Cross.", context: 'Post-surgery follow-up scheduling' },
      { script: "This is Maria Lopez calling. I received a bill for $840 for my MRI but my insurance should have covered most of it. Can you explain what happened? My member ID is BCB-4471902.", context: 'Billing/insurance dispute' },
      { script: "I need to get my medical records sent to a new specialist I'm seeing next week. Can you help me with that? I'll need them by Tuesday.", context: 'Medical records request' },
    ],
    roleplayScenarios: [
      { customerLine: "I've been waiting for 45 minutes past my appointment time. I took time off work for this. This is unacceptable!", context: 'Frustrated patient', emotion: 'angry' },
      { customerLine: "I'm worried about these test results. The nurse said someone would call me back but nobody has. I can't sleep I'm so anxious.", context: 'Anxious patient awaiting results', emotion: 'anxious' },
      { customerLine: "I need to speak to the doctor right now. My mother is a patient and I need to know her medication dosage. It's urgent.", context: 'Family member requesting info', emotion: 'urgent' },
    ],
    scoringWeights: { 'Medical Knowledge': 1.3, 'Customer Service': 1.2, Empathy: 1.2, Professionalism: 1.2, Listening: 1.1, Confidentiality: 1.3 },
    keyCompetencies: ['HIPAA compliance', 'Medical scheduling', 'Insurance verification', 'Patient empathy', 'Medical terminology'],
    coachingFocus: ['HIPAA-compliant communication', 'Patient empathy', 'Medical terminology precision'],
    recommendedLearningPath: ['Medical VA fundamentals', 'HIPAA compliance training', 'Medical terminology', 'Patient communication'],
  },
  {
    id: 'real-estate-va',
    label: 'Real Estate VA',
    category: 'Real Estate',
    description: 'Property listings, lead management, and agent support.',
    interviewQuestions: [
      "Tell me about your real estate VA experience.",
      "How would you handle a lead who wants to see a property immediately?",
      "How do you manage property listings across multiple platforms?",
      "How would you handle a seller who is unhappy with their listing performance?",
      "How do you screen potential buyers over the phone?",
      "How would you coordinate a property showing?",
      "How do you handle a buyer who keeps changing their requirements?",
      "How would you follow up with cold real estate leads?",
      "How do you manage a real estate agent's busy schedule?",
      "How would you handle a call about a property that's already under contract?",
      "How do you handle a difficult seller who won't accept an offer?",
      "How would you manage open house logistics?",
      "How do you handle a buyer who wants to negotiate after inspection?",
      "How do you organize transaction documents?",
      "What makes a great real estate VA?",
    ],
    listeningScenarios: [
      { script: "Hi, I saw the listing for the property on Maple Street. I'm very interested and I'd like to see it as soon as possible. I'm pre-approved for $450K. Can we schedule a showing this weekend?", context: 'Hot buyer lead' },
      { script: "Our house has been on the market for 90 days and we've only had two showings. We're thinking about switching agents. What can you tell me about your marketing strategy?", context: 'Frustrated seller' },
      { script: "I submitted an offer on the Oak Lane property yesterday. The seller countered at $420K. We want to accept but we need 24 hours to move some money around. Can you let the seller know?", context: 'Offer negotiation' },
    ],
    roleplayScenarios: [
      { customerLine: "I've been trying to reach the agent for three days about my offer. This is a time-sensitive deal and I need an answer now!", context: 'Urgent buyer', emotion: 'frustrated' },
      { customerLine: "I'm not happy with how the listing photos turned out. The house looks dark and uninviting. What are we going to do about this?", context: 'Unhappy seller', emotion: 'disappointed' },
      { customerLine: "I'm just browsing right now. I don't want to commit to anything. Can you just send me some listings and leave me alone?", context: 'Casual browser', emotion: 'casual' },
    ],
    scoringWeights: { 'Customer Service': 1.2, Communication: 1.2, 'Problem Solving': 1.1, Listening: 1.1, Professionalism: 1.1, 'Real Estate Knowledge': 1.2 },
    keyCompetencies: ['Lead management', 'Listing coordination', 'Transaction support', 'Client communication', 'Scheduling'],
    coachingFocus: ['Lead qualification', 'Client follow-up', 'Real estate terminology'],
    recommendedLearningPath: ['Real estate VA fundamentals', 'Lead management systems', 'Transaction coordination', 'Real estate terminology'],
  },
  {
    id: 'ecommerce-va',
    label: 'E-commerce VA',
    category: 'E-commerce',
    description: 'Order management, customer inquiries, and product listings.',
    interviewQuestions: [
      "Tell me about your e-commerce VA experience.",
      "How would you handle a customer whose order was lost in transit?",
      "How do you manage product listings across multiple platforms?",
      "How would you handle a high volume of returns during the holidays?",
      "How do you handle inventory discrepancies?",
      "How would you respond to a negative product review?",
      "How do you handle a customer who wants to cancel an order after it's shipped?",
      "How would you handle a customer who received the wrong item?",
      "How do you manage a product launch?",
      "How would you handle a supplier communication issue?",
      "How do you handle a customer who wants a discount on a full-price item?",
      "How would you handle a chargeback dispute?",
      "How do you manage customer inquiries across multiple channels?",
      "How would you handle a product that's backordered?",
      "What makes a great e-commerce VA?",
    ],
    listeningScenarios: [
      { script: "I ordered a blender two weeks ago and the tracking hasn't updated in 6 days. I need it for a party this weekend. Order number is EC-88210. What's going on?", context: 'Lost order inquiry' },
      { script: "I received the wrong size shoes. I ordered a size 8 but got a size 10. I need the correct size by next week for an event. How do we fix this?", context: 'Wrong item received' },
      { script: "I want to return this jacket but the return window closed two days ago. I've been sick and couldn't get to it in time. Is there anything you can do?", context: 'Late return request' },
    ],
    roleplayScenarios: [
      { customerLine: "This is the third time you've sent me the wrong item. I want a full refund and I'm never shopping here again!", context: 'Repeat wrong order', emotion: 'angry' },
      { customerLine: "I really want this jacket but it's $180. That's a lot. Is there any way you can give me a discount? I'm a loyal customer.", context: 'Discount request', emotion: 'hopeful' },
      { customerLine: "My order says delivered but it's not here. I've checked everywhere. Did the driver leave it somewhere? I have a doorbell camera.", context: 'Missing delivery', emotion: 'confused' },
    ],
    scoringWeights: { 'Customer Service': 1.3, 'Problem Solving': 1.2, Communication: 1.1, Listening: 1.1, 'E-commerce Knowledge': 1.2, Professionalism: 1.0 },
    keyCompetencies: ['Order management', 'Return processing', 'Listing management', 'Customer communication', 'Inventory tracking'],
    coachingFocus: ['Order issue resolution', 'Review response etiquette', 'Multi-channel management'],
    recommendedLearningPath: ['E-commerce VA fundamentals', 'Order management systems', 'Customer service for retail', 'Inventory management'],
  },
  {
    id: 'social-media-va',
    label: 'Social Media VA',
    category: 'Marketing',
    description: 'Content scheduling, community management, and brand engagement.',
    interviewQuestions: [
      "Tell me about your social media VA experience.",
      "How do you handle a negative comment on a client's post?",
      "How would you manage a content calendar for multiple clients?",
      "How do you handle a brand crisis on social media?",
      "How would you respond to a customer complaint via DM?",
      "How do you handle a troll or abusive commenter?",
      "How would you handle a client who wants to go viral?",
      "How do you stay current with social media trends?",
      "How would you handle a scheduling mistake on a client's account?",
      "How do you handle a client who keeps changing their brand voice?",
      "How would you handle an influencer outreach campaign?",
      "How do you manage engagement across multiple platforms?",
      "How would you handle a post that's getting negative backlash?",
      "How do you handle a client who wants to post something controversial?",
      "What makes a great social media VA?",
    ],
    listeningScenarios: [
      { script: "Hi, I'm a small business owner and I need help with my Instagram. I post maybe once a week and I'm not getting any engagement. I sell handmade jewelry. Can you help me grow my account?", context: 'New client social media inquiry' },
      { script: "We have a product launch next Tuesday at 10 AM. I need posts ready for Instagram, Facebook, and Twitter. The copy needs to be punchy and the hashtags need to be researched. Can you handle this?", context: 'Product launch coordination' },
      { script: "Someone left a really nasty comment on our latest post about our customer service. It's getting likes and other people are piling on. What should we do?", context: 'Negative comment crisis' },
    ],
    roleplayScenarios: [
      { customerLine: "I told you I wanted a fun, casual tone and this post sounds like a corporate robot wrote it. I'm not happy with this.", context: 'Unhappy with brand voice', emotion: 'disappointed' },
      { customerLine: "A competitor just copied our post almost word for word. What do we do? Do we call them out publicly?", context: 'Brand crisis', emotion: 'angry' },
      { customerLine: "I want to post something that's a little edgy and might get some backlash. I think it'll get engagement. What do you think?", context: 'Controversial content request', emotion: 'excited' },
    ],
    scoringWeights: { Communication: 1.3, 'Customer Service': 1.1, Creativity: 1.2, Professionalism: 1.1, Listening: 1.0, 'Social Media Knowledge': 1.2 },
    keyCompetencies: ['Content scheduling', 'Community management', 'Crisis handling', 'Brand voice', 'Engagement strategy'],
    coachingFocus: ['Brand voice consistency', 'Crisis response', 'Diplomatic community management'],
    recommendedLearningPath: ['Social media management fundamentals', 'Crisis communication', 'Content strategy', 'Community management'],
  },
  {
    id: 'bookkeeper',
    label: 'Bookkeeper',
    category: 'Finance',
    description: 'Financial records, invoicing, and client communication.',
    interviewQuestions: [
      "Tell me about your bookkeeping experience.",
      "How do you handle a discrepancy in a client's accounts?",
      "How would you explain a financial report to a non-financial client?",
      "How do you handle a client who is disorganized with their receipts?",
      "How would you handle a client who is late providing documents?",
      "How do you ensure accuracy in your bookkeeping?",
      "How would you handle a client who questions your billing?",
      "How do you handle confidential financial information?",
      "How would you handle a client who wants to 'creative' with their expenses?",
      "How do you manage multiple clients' books simultaneously?",
      "How would you handle a client who is behind on their taxes?",
      "How do you handle reconciling a messy bank statement?",
      "How would you handle a client who wants to do bookkeeping themselves to save money?",
      "How do you stay updated on tax regulations?",
      "What makes a great bookkeeper?",
    ],
    listeningScenarios: [
      { script: "I have a question about my monthly financial report. There's a line item here for $2,400 that I don't recognize. It says 'office supplies' but I didn't buy that much. Can you look into it?", context: 'Report discrepancy inquiry' },
      { script: "I'm behind on three months of bookkeeping and I'm feeling overwhelmed. I have a shoebox of receipts. Can you help me get caught up before tax season?", context: 'Disorganized client' },
      { script: "I think my previous bookkeeper made some mistakes on last year's books. I'm worried about an audit. Can you review everything and fix what's wrong?", context: 'Cleanup and review request' },
    ],
    roleplayScenarios: [
      { customerLine: "I don't understand this profit and loss statement. I'm not a numbers person. Can you explain it to me like I'm five?", context: 'Confused client', emotion: 'confused' },
      { customerLine: "I want to categorize some personal expenses as business expenses to reduce my tax bill. Everyone does it, right?", context: 'Ethics boundary', emotion: 'casual' },
      { customerLine: "I've been waiting two weeks for you to finish my books. I have a meeting with my accountant on Friday. Where are we on this?", context: 'Frustrated by delay', emotion: 'frustrated' },
    ],
    scoringWeights: { 'Financial Accuracy': 1.4, Professionalism: 1.2, Communication: 1.2, 'Problem Solving': 1.1, Listening: 1.0, Confidentiality: 1.2 },
    keyCompetencies: ['Financial accuracy', 'Client communication', 'Software proficiency', 'Confidentiality', 'Problem solving'],
    coachingFocus: ['Plain-language financial explanations', 'Professional boundaries', 'Accuracy verification'],
    recommendedLearningPath: ['Bookkeeping fundamentals', 'Financial software proficiency', 'Client communication', 'Tax basics'],
  },
  {
    id: 'data-entry',
    label: 'Data Entry Specialist',
    category: 'Administrative',
    description: 'Accurate data input, verification, and database management.',
    interviewQuestions: [
      "Tell me about your data entry experience.",
      "How do you ensure accuracy when entering large volumes of data?",
      "How do you handle repetitive tasks without losing focus?",
      "How would you handle a database with inconsistent formatting?",
      "How do you handle a data entry error you discovered after submission?",
      "How would you prioritize data entry tasks?",
      "How do you handle confidential data?",
      "How would you handle a task with unclear instructions?",
      "How do you manage your time during high-volume data entry?",
      "How would you handle a client who wants data entered faster but with no errors?",
      "How do you handle data entry across multiple systems?",
      "How would you handle a data migration project?",
      "How do you handle a system crash while entering data?",
      "How do you stay motivated during repetitive work?",
      "What makes a great data entry specialist?",
    ],
    listeningScenarios: [
      { script: "I have a spreadsheet with 500 customer records that need to be entered into our CRM by end of day. The formatting is inconsistent and some fields are missing. Can you handle this?", context: 'High-volume data entry task' },
      { script: "We're migrating from our old system to a new database. I need all 2,000 product records transferred accurately. There are custom fields that need to be mapped correctly.", context: 'Data migration project' },
      { script: "I noticed some errors in the data you entered last week. Several customer phone numbers are wrong. We need to fix this before the marketing campaign goes out.", context: 'Error discovery' },
    ],
    roleplayScenarios: [
      { customerLine: "I need this done by 5 PM today. That's 1,000 records in four hours. Can you do it or not?", context: 'Tight deadline pressure', emotion: 'demanding' },
      { customerLine: "The data you entered has too many errors. I'm starting to lose trust. How do we fix this and make sure it doesn't happen again?", context: 'Quality concerns', emotion: 'frustrated' },
      { customerLine: "I don't have clear instructions for this task. Can you just figure it out? I trust your judgment.", context: 'Vague instructions', emotion: 'casual' },
    ],
    scoringWeights: { 'Data Accuracy': 1.4, 'Attention to Detail': 1.3, Professionalism: 1.1, Communication: 1.0, Listening: 1.0, 'Time Management': 1.2 },
    keyCompetencies: ['Data accuracy', 'Speed with precision', 'Software proficiency', 'Focus', 'Confidentiality'],
    coachingFocus: ['Accuracy verification techniques', 'Focus maintenance', 'Clear task clarification'],
    recommendedLearningPath: ['Data entry fundamentals', 'Speed typing techniques', 'Data verification', 'Software proficiency'],
  },
];

export const POSITION_LABELS = POSITIONS.map((p) => p.label);

export function getPosition(id: PositionId): PositionConfig {
  return POSITIONS.find((p) => p.id === id) ?? POSITIONS.find((p) => p.id === 'general-va') ?? POSITIONS[0];
}

export function getPositionByLabel(label: string): PositionConfig | null {
  return POSITIONS.find((p) => p.label === label) ?? null;
}
